# Register a Windows Scheduled Task that runs both PriceOye and Daraz
# spiders every 12 hours and finalises scrape_run / scrape_errors records
# through the backend. Must be run from an Administrator PowerShell —
# user tasks need elevation to register, even when they run under the
# interactive user.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\install_scrape_schedule.ps1
#   powershell -ExecutionPolicy Bypass -File .\install_scrape_schedule.ps1 -Uninstall
#
# Each run writes a timestamped log to %LOCALAPPDATA%\vextro_scrape_logs
# so the FYP evaluator can see exactly when, and how long, each cycle
# took to complete.

param(
    [string] $TaskName    = 'VEXTRO_Scraper_Every_12h',
    [string] $RepoRoot    = 'D:\work\vextro-claude\vextro',
    [string] $StartAt     = '04:00',
    [string] $ApiUrl      = 'http://127.0.0.1:8000',
    [switch] $Uninstall
)

$ErrorActionPreference = 'Stop'

$principal = New-Object Security.Principal.WindowsPrincipal(
    [Security.Principal.WindowsIdentity]::GetCurrent()
)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "Run this in an Administrator PowerShell."
    exit 1
}

if ($Uninstall) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Unregistered: $TaskName" -ForegroundColor Yellow
    } else {
        Write-Host "No such task: $TaskName" -ForegroundColor DarkGray
    }
    exit 0
}

$scraperDir = Join-Path $RepoRoot 'vextro_scraper'
$backendEnv = Join-Path $RepoRoot 'backend\.env'
$venvPython = Join-Path $RepoRoot 'backend\.venv\Scripts\python.exe'

if (-not (Test-Path $scraperDir)) { throw "Scraper dir not found: $scraperDir" }
if (-not (Test-Path $backendEnv)) { throw "Backend .env not found: $backendEnv" }
if (-not (Test-Path $venvPython)) { throw "Backend venv not found: $venvPython" }

# Generate a wrapper .ps1 that loads INGESTION_API_KEY from backend/.env,
# then runs both spiders. We write this to a stable location so the
# Scheduled Task action points at a real file (Task Scheduler cannot
# host complex inline PowerShell).
$wrapperPath = Join-Path $scraperDir 'run_scheduled_scrape.ps1'
$wrapperSource = @"
# AUTO-GENERATED by install_scrape_schedule.ps1 — safe to overwrite.
`$ErrorActionPreference = 'Continue'
`$ts = Get-Date -Format 'yyyyMMdd_HHmmss'
`$logDir = Join-Path `$env:LOCALAPPDATA 'vextro_scrape_logs'
if (-not (Test-Path `$logDir)) { New-Item -ItemType Directory -Path `$logDir -Force | Out-Null }
`$log = Join-Path `$logDir "scrape_`$ts.log"

Set-Location "$scraperDir"

# Load INGESTION_API_KEY from backend/.env so the acquisition POSTs are
# accepted by the backend.
Get-Content "$backendEnv" | ForEach-Object {
    if (`$_ -match '^(\w+)=(.*)$') {
        `$env:(`$matches[1]) = `$matches[2]
    }
}
`$env:VEXTRO_API_URL = '$ApiUrl'
`$env:VEXTRO_SCRAPE_TRIGGER = 'scheduler'

"Scrape cycle started `$ts" | Tee-Object -FilePath `$log

foreach (`$spider in @('priceoye_smartphones','daraz_smartphones')) {
    "--- `$spider ---" | Tee-Object -FilePath `$log -Append
    & "$venvPython" -m scrapy crawl `$spider 2>&1 | Tee-Object -FilePath `$log -Append
}

"Scrape cycle finished `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" | Tee-Object -FilePath `$log -Append
"@
Set-Content -Path $wrapperPath -Value $wrapperSource -Encoding utf8

$action = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""

$trigger = New-ScheduledTaskTrigger -Daily -At $StartAt
$trigger.Repetition = (New-ScheduledTaskTrigger -Once -At $StartAt `
    -RepetitionInterval (New-TimeSpan -Hours 12) `
    -RepetitionDuration ([TimeSpan]::MaxValue)).Repetition

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 1)

$principalTask = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principalTask `
    -Description "Run PriceOye + Daraz spiders every 12 hours against the local backend." | Out-Null

Write-Host "Registered '$TaskName' (first run $StartAt, then every 12h)." -ForegroundColor Green
Write-Host "Wrapper script: $wrapperPath" -ForegroundColor DarkGray
Write-Host "Logs land in : $env:LOCALAPPDATA\vextro_scrape_logs" -ForegroundColor DarkGray
Write-Host "Run once now : Start-ScheduledTask -TaskName $TaskName" -ForegroundColor DarkGray
Write-Host "Uninstall    : .\install_scrape_schedule.ps1 -Uninstall" -ForegroundColor DarkGray
