"""create sales imports and records

Revision ID: 264812e85407
Revises: e989e5b4255c
Create Date: 2026-08-06 23:29:53.415369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264812e85407'
down_revision: Union[str, Sequence[str], None] = 'e989e5b4255c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_imports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('accepted_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'completed_with_errors', 'failed')", name='ck_sales_imports_status_valid'),
    sa.CheckConstraint('accepted_rows + rejected_rows <= total_rows', name='ck_sales_imports_processed_rows_within_total'),
    sa.CheckConstraint('accepted_rows >= 0', name='ck_sales_imports_accepted_rows_non_negative'),
    sa.CheckConstraint('rejected_rows >= 0', name='ck_sales_imports_rejected_rows_non_negative'),
    sa.CheckConstraint('total_rows >= 0', name='ck_sales_imports_total_rows_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_imports_organization_id'), 'sales_imports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sales_imports_status'), 'sales_imports', ['status'], unique=False)
    op.create_index(op.f('ix_sales_imports_uploaded_by_user_id'), 'sales_imports', ['uploaded_by_user_id'], unique=False)
    op.create_table('sales_records',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sales_import_id', sa.BigInteger(), nullable=False),
    sa.Column('business_product_id', sa.BigInteger(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'PKR'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_records_quantity_positive'),
    sa.CheckConstraint('source_row_number >= 1', name='ck_sales_records_source_row_positive'),
    sa.CheckConstraint('total_revenue >= 0', name='ck_sales_records_total_revenue_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_records_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['business_product_id'], ['business_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_import_id'], ['sales_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_import_id', 'source_row_number', name='uq_sales_records_import_source_row')
    )
    op.create_index(op.f('ix_sales_records_business_product_id'), 'sales_records', ['business_product_id'], unique=False)
    op.create_index(op.f('ix_sales_records_sale_date'), 'sales_records', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_records_sales_import_id'), 'sales_records', ['sales_import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_records_sales_import_id'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_sale_date'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_business_product_id'), table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index(op.f('ix_sales_imports_uploaded_by_user_id'), table_name='sales_imports')
    op.drop_index(op.f('ix_sales_imports_status'), table_name='sales_imports')
    op.drop_index(op.f('ix_sales_imports_organization_id'), table_name='sales_imports')
    op.drop_table('sales_imports')
    # ### end Alembic commands ###
