
"""create price alerts

Revision ID: 3894a39014cf
Revises: 3ea43f8e05f1
Create Date: 2026-07-31 00:22:16.142056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3894a39014cf'
down_revision: Union[str, Sequence[str], None] = '3ea43f8e05f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_product_id', sa.BigInteger(), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'PKR'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notification_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                canonical_product_id IS NOT NULL\n                AND listing_id IS NULL\n            )\n            OR\n            (\n                canonical_product_id IS NULL\n                AND listing_id IS NOT NULL\n            )\n            ', name='ck_price_alerts_exactly_one_target'),
    sa.CheckConstraint('char_length(currency) = 3', name='ck_price_alerts_currency_length'),
    sa.CheckConstraint('notification_count >= 0', name='ck_price_alerts_notification_count_non_negative'),
    sa.CheckConstraint('target_price > 0', name='ck_price_alerts_target_price_positive'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_canonical_product_id'), 'price_alerts', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_price_alerts_listing_id'), 'price_alerts', ['listing_id'], unique=False)
    op.create_index('ix_price_alerts_user_active', 'price_alerts', ['user_id', 'is_active'], unique=False)
    op.create_index('uq_price_alerts_active_listing_target', 'price_alerts', ['user_id', 'listing_id'], unique=True, postgresql_where=sa.text('is_active = true AND listing_id IS NOT NULL'))
    op.create_index('uq_price_alerts_active_product_target', 'price_alerts', ['user_id', 'canonical_product_id'], unique=True, postgresql_where=sa.text('is_active = true AND canonical_product_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_price_alerts_active_product_target', table_name='price_alerts', postgresql_where=sa.text('is_active = true AND canonical_product_id IS NOT NULL'))
    op.drop_index('uq_price_alerts_active_listing_target', table_name='price_alerts', postgresql_where=sa.text('is_active = true AND listing_id IS NOT NULL'))
    op.drop_index('ix_price_alerts_user_active', table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_listing_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_canonical_product_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    # ### end Alembic commands ###
