"""create price history

Revision ID: 3ea43f8e05f1
Revises: e3398bfcc157
Create Date: 2026-07-30 23:37:00.856095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea43f8e05f1'
down_revision: Union[str, Sequence[str], None] = 'e3398bfcc157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'PKR'"), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source', sa.String(length=50), server_default=sa.text("'scraper'"), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='ck_price_history_currency_length'),
    sa.CheckConstraint('original_price IS NULL OR original_price >= 0', name='ck_price_history_original_price_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_price_history_price_non_negative'),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_listing_captured_at', 'price_history', ['listing_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_history_listing_captured_at', table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
