"""create canonical products and variants

Revision ID: 72c322c2384b
Revises: 230caa8e6095
Create Date: 2026-07-30 18:45:40.795440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72c322c2384b'
down_revision: Union[str, Sequence[str], None] = '230caa8e6095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'model', name='uq_canonical_products_brand_model')
    )
    op.create_index(op.f('ix_canonical_products_brand_id'), 'canonical_products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_canonical_products_category_id'), 'canonical_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_canonical_products_model'), 'canonical_products', ['model'], unique=False)
    op.create_index(op.f('ix_canonical_products_name'), 'canonical_products', ['name'], unique=False)
    op.create_index(op.f('ix_canonical_products_slug'), 'canonical_products', ['slug'], unique=True)
    op.create_table('product_variants',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('canonical_product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=30), server_default=sa.text("'new'"), nullable=False),
    sa.Column('variant_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ram_gb IS NULL OR ram_gb > 0', name='ck_product_variants_ram_positive'),
    sa.CheckConstraint('storage_gb IS NULL OR storage_gb > 0', name='ck_product_variants_storage_positive'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_product_id', 'ram_gb', 'storage_gb', 'color', 'condition', name='uq_product_variants_configuration')
    )
    op.create_index(op.f('ix_product_variants_canonical_product_id'), 'product_variants', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_canonical_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_canonical_products_slug'), table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_name'), table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_model'), table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_category_id'), table_name='canonical_products')
    op.drop_index(op.f('ix_canonical_products_brand_id'), table_name='canonical_products')
    op.drop_table('canonical_products')
    # ### end Alembic commands ###
