"""create sellers and product listings

Revision ID: 9695d975d0ab
Revises: 72c322c2384b
Create Date: 2026-07-30 19:00:04.907931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9695d975d0ab'
down_revision: Union[str, Sequence[str], None] = '72c322c2384b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('platform_id', sa.BigInteger(), nullable=False),
    sa.Column('external_seller_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name='ck_sellers_rating_range'),
    sa.CheckConstraint('review_count >= 0', name='ck_sellers_review_count_non_negative'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'external_seller_id', name='uq_sellers_platform_external_id')
    )
    op.create_index(op.f('ix_sellers_name'), 'sellers', ['name'], unique=False)
    op.create_index(op.f('ix_sellers_platform_id'), 'sellers', ['platform_id'], unique=False)
    op.create_table('product_listings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('platform_id', sa.BigInteger(), nullable=False),
    sa.Column('product_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'PKR'"), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('warranty', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_price >= 0', name='ck_product_listings_current_price_non_negative'),
    sa.CheckConstraint('original_price IS NULL OR original_price >= 0', name='ck_product_listings_original_price_non_negative'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name='ck_product_listings_rating_range'),
    sa.CheckConstraint('review_count >= 0', name='ck_product_listings_review_count_non_negative'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'external_id', name='uq_product_listings_platform_external_id')
    )
    op.create_index(op.f('ix_product_listings_platform_id'), 'product_listings', ['platform_id'], unique=False)
    op.create_index(op.f('ix_product_listings_product_variant_id'), 'product_listings', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_product_listings_seller_id'), 'product_listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_product_listings_title'), 'product_listings', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_listings_title'), table_name='product_listings')
    op.drop_index(op.f('ix_product_listings_seller_id'), table_name='product_listings')
    op.drop_index(op.f('ix_product_listings_product_variant_id'), table_name='product_listings')
    op.drop_index(op.f('ix_product_listings_platform_id'), table_name='product_listings')
    op.drop_table('product_listings')
    op.drop_index(op.f('ix_sellers_platform_id'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_name'), table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###
