"""create product images

Revision ID: e3398bfcc157
Revises: 9695d975d0ab
Create Date: 2026-07-30 19:18:37.570771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3398bfcc157'
down_revision: Union[str, Sequence[str], None] = '9695d975d0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('canonical_product_id', sa.BigInteger(), nullable=True),
    sa.Column('listing_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                canonical_product_id IS NOT NULL\n                AND listing_id IS NULL\n            )\n            OR\n            (\n                canonical_product_id IS NULL\n                AND listing_id IS NOT NULL\n            )\n            ', name='ck_product_images_exactly_one_owner'),
    sa.CheckConstraint('sort_order >= 0', name='ck_product_images_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_canonical_product_id'), 'product_images', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_product_images_listing_id'), 'product_images', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_listing_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_canonical_product_id'), table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
