"""add SME business intelligence core tables

Revision ID: e989e5b4255c
Revises: 3894a39014cf
Create Date: 2026-08-06 01:38:59.530576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e989e5b4255c'
down_revision: Union[str, Sequence[str], None] = '3894a39014cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('business_products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_product_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'PKR'"), nullable=False),
    sa.Column('stock_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reorder_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_price IS NULL OR cost_price >= 0', name='ck_business_products_cost_price_non_negative'),
    sa.CheckConstraint('reorder_level >= 0', name='ck_business_products_reorder_level_non_negative'),
    sa.CheckConstraint('selling_price IS NULL OR selling_price >= 0', name='ck_business_products_selling_price_non_negative'),
    sa.CheckConstraint('stock_level >= 0', name='ck_business_products_stock_level_non_negative'),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonical_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sku', name='uq_business_products_organization_sku')
    )
    op.create_index(op.f('ix_business_products_canonical_product_id'), 'business_products', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_business_products_is_active'), 'business_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_business_products_name'), 'business_products', ['name'], unique=False)
    op.create_index(op.f('ix_business_products_organization_id'), 'business_products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_business_products_sku'), 'business_products', ['sku'], unique=False)
    op.create_table('organization_users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('membership_role', sa.String(length=30), server_default=sa.text("'analyst'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("membership_role IN ('owner', 'manager', 'analyst')", name='ck_organization_users_membership_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_users_organization_user')
    )
    op.create_index(op.f('ix_organization_users_is_active'), 'organization_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_users_organization_id'), 'organization_users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_users_user_id'), 'organization_users', ['user_id'], unique=False)
    op.create_table('competitor_watchlists',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('business_product_id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_product_id'], ['business_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'business_product_id', 'listing_id', name='uq_competitor_watchlists_organization_product_listing')
    )
    op.create_index(op.f('ix_competitor_watchlists_business_product_id'), 'competitor_watchlists', ['business_product_id'], unique=False)
    op.create_index(op.f('ix_competitor_watchlists_is_active'), 'competitor_watchlists', ['is_active'], unique=False)
    op.create_index(op.f('ix_competitor_watchlists_listing_id'), 'competitor_watchlists', ['listing_id'], unique=False)
    op.create_index(op.f('ix_competitor_watchlists_organization_id'), 'competitor_watchlists', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_watchlists_organization_id'), table_name='competitor_watchlists')
    op.drop_index(op.f('ix_competitor_watchlists_listing_id'), table_name='competitor_watchlists')
    op.drop_index(op.f('ix_competitor_watchlists_is_active'), table_name='competitor_watchlists')
    op.drop_index(op.f('ix_competitor_watchlists_business_product_id'), table_name='competitor_watchlists')
    op.drop_table('competitor_watchlists')
    op.drop_index(op.f('ix_organization_users_user_id'), table_name='organization_users')
    op.drop_index(op.f('ix_organization_users_organization_id'), table_name='organization_users')
    op.drop_index(op.f('ix_organization_users_is_active'), table_name='organization_users')
    op.drop_table('organization_users')
    op.drop_index(op.f('ix_business_products_sku'), table_name='business_products')
    op.drop_index(op.f('ix_business_products_organization_id'), table_name='business_products')
    op.drop_index(op.f('ix_business_products_name'), table_name='business_products')
    op.drop_index(op.f('ix_business_products_is_active'), table_name='business_products')
    op.drop_index(op.f('ix_business_products_canonical_product_id'), table_name='business_products')
    op.drop_table('business_products')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
